import { chromium } from 'playwright'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
const page = await ctx.newPage()
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
await page.goto('http://localhost:4173/')
await page.waitForFunction(() => navigator.serviceWorker?.controller || navigator.serviceWorker?.ready.then(() => true), null, { timeout: 30000 })
// wait for precache to finish
await page.waitForFunction(async () => { const keys = await caches.keys(); for (const k of keys) { const c = await caches.open(k); const reqs = await c.keys(); if (reqs.some((r) => r.url.includes('world.json'))) return true } return false }, null, { timeout: 60000, polling: 1000 })
console.log('precached')
await ctx.setOffline(true)
await page.reload()
await page.waitForTimeout(1500)
await page.getByText('New Career').first().click()
await page.waitForSelector('input[placeholder="First name"]', { timeout: 30000 })
await page.fill('input[placeholder="First name"]', 'Off'); await page.fill('input[placeholder="Last name"]', 'Line')
await page.getByText('Continue').first().click(); await page.getByText('Serie A').first().click(); await page.locator('.club-card').nth(0).click()
await page.getByRole('button', { name: /^Manage/ }).click(); await page.getByText('Continue').first().click(); await page.getByText('Start Career').first().click()
await page.waitForSelector('.continue-btn', { timeout: 60000 })
const title = await page.locator('.topbar .title').first().innerText()
console.log('offline career started:', title)
const badges = await page.evaluate(() => [...document.querySelectorAll('img.badge-img')].filter((i) => i.complete && i.naturalWidth > 0).length)
console.log('crests rendered offline:', badges)
console.log(errors.length ? errors.join('\n') : 'no errors')
await browser.close()
